// 모듈 소스 → 단일 번들 변환 스크립트
// Usage: node scripts/build.js

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUTPUT = path.join(ROOT, 'app.bundle.js');

// 의존성 순서대로 나열
const files = [
  path.join(ROOT, 'data.js'),
  path.join(SRC, 'config.js'),
  path.join(SRC, 'state.js'),
  path.join(SRC, 'persistence.js'),
  path.join(SRC, 'scoring.js'),
  path.join(SRC, 'officers.js'),
  path.join(SRC, 'assignment.js'),
  path.join(SRC, 'renderers.js'),
  path.join(SRC, 'main.js'),
];

function stripImportsExports(code) {
  return code
    .split('\n')
    .filter(line => !line.match(/^\s*import\s+.*from\s+/))
    .join('\n')
    .replace(/export\s+(const|let|var|function|class)\s/g, '$1 ');
}

let output = '// Bundled from src/ modules — auto-generated by scripts/build.js\n';
output += '// Do not edit manually. Edit src/*.js then run: node scripts/build.js\n\n';

for (const file of files) {
  const code = fs.readFileSync(file, 'utf-8');
  const stripped = stripImportsExports(code);
  const name = path.relative(ROOT, file).replace(/\\/g, '/');
  output += `// ===== ${name} =====\n\n${stripped}\n\n`;
}

fs.writeFileSync(OUTPUT, output, 'utf-8');
const lines = output.split('\n').length;
console.log(`Built ${path.basename(OUTPUT)} (${lines} lines)`);
